name: GitHub Readme YouTube Cards
on:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Allow the job to commit to the repository
    permissions:
      contents: write
    # Run the GitHub Readme YouTube Cards action
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCNbsmTeTisXb_hFTrulkTCg
          commet_tag_name: YOUTUBE-CARDS
      - run: echo OUTPUT '${{ steps.youtube-cards.outputs.markdown}}'
        shell: bash
